"""add subscription plan system

Revision ID: a506db480a32
Revises: 0fd8b3c06bad
Create Date: 2026-02-16 23:24:52.699765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a506db480a32'
down_revision: Union[str, Sequence[str], None] = '0fd8b3c06bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.add_column('stores', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('subscription_start', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'stores', ['whatsapp_number'])
    op.create_foreign_key(None, 'stores', 'subscription_plans', ['subscription_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_column('stores', 'subscription_plan_id')
    op.drop_column('stores', 'subscription_end')
    op.drop_column('stores', 'subscription_start')
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'whatsapp_number')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
